create table if not exists public.terms_documents (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  version integer not null unique check (version > 0),
  file_name text not null,
  storage_path text not null unique,
  extracted_text text not null check (length(trim(extracted_text)) >= 50),
  content_hash text,
  is_active boolean not null default false,
  published_by uuid references auth.users(id) on delete set null,
  published_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create unique index if not exists terms_documents_one_active_idx
  on public.terms_documents (is_active)
  where is_active;

create table if not exists public.terms_acceptances (
  id bigint generated by default as identity primary key,
  terms_document_id uuid not null references public.terms_documents(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete cascade,
  acceptance_context text not null check (acceptance_context in ('activation', 'checkout')),
  item_id uuid references public.items(id) on delete set null,
  booking_id uuid references public.bookings(id) on delete set null,
  accepted_at timestamptz not null default now(),
  user_agent text
);

create index if not exists terms_acceptances_user_idx
  on public.terms_acceptances (user_id, accepted_at desc);

create index if not exists terms_acceptances_document_idx
  on public.terms_acceptances (terms_document_id, accepted_at desc);

alter table public.terms_documents enable row level security;
alter table public.terms_acceptances enable row level security;

drop policy if exists "Public reads active terms" on public.terms_documents;
create policy "Public reads active terms"
on public.terms_documents for select
to anon, authenticated
using (is_active);

drop policy if exists "Admins manage terms documents" on public.terms_documents;
create policy "Admins manage terms documents"
on public.terms_documents for all
to authenticated
using (
  exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid()) and lower(p.role::text) = 'admin'
  )
)
with check (
  exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid()) and lower(p.role::text) = 'admin'
  )
);

drop policy if exists "Users record their own terms acceptance" on public.terms_acceptances;
create policy "Users record their own terms acceptance"
on public.terms_acceptances for insert
to authenticated
with check (
  user_id = (select auth.uid())
  and exists (
    select 1 from public.terms_documents d
    where d.id = terms_document_id and d.is_active
  )
);

drop policy if exists "Users read their own terms acceptance" on public.terms_acceptances;
create policy "Users read their own terms acceptance"
on public.terms_acceptances for select
to authenticated
using (
  user_id = (select auth.uid())
  or exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid()) and lower(p.role::text) = 'admin'
  )
);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'terms-documents',
  'terms-documents',
  false,
  10485760,
  array['application/pdf']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "Admins upload terms PDFs" on storage.objects;
create policy "Admins upload terms PDFs"
on storage.objects for insert
to authenticated
with check (
  bucket_id = 'terms-documents'
  and exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid()) and lower(p.role::text) = 'admin'
  )
);

drop policy if exists "Admins read terms PDFs" on storage.objects;
create policy "Admins read terms PDFs"
on storage.objects for select
to authenticated
using (
  bucket_id = 'terms-documents'
  and exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid()) and lower(p.role::text) = 'admin'
  )
);

drop policy if exists "Admins delete terms PDFs" on storage.objects;
create policy "Admins delete terms PDFs"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'terms-documents'
  and exists (
    select 1 from public.profiles p
    where p.id = (select auth.uid()) and lower(p.role::text) = 'admin'
  )
);

create or replace function public.publish_terms_document(
  requested_title text,
  requested_file_name text,
  requested_storage_path text,
  requested_extracted_text text,
  requested_content_hash text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  next_version integer;
  published_id uuid;
begin
  if not exists (
    select 1 from public.profiles p
    where p.id = auth.uid() and lower(p.role::text) = 'admin'
  ) then
    raise exception 'Administrator access is required.';
  end if;

  if length(trim(coalesce(requested_title, ''))) < 3
     or length(trim(coalesce(requested_file_name, ''))) < 5
     or length(trim(coalesce(requested_storage_path, ''))) < 5
     or length(trim(coalesce(requested_extracted_text, ''))) < 50 then
    raise exception 'A title, PDF file, storage path, and extracted terms text are required.';
  end if;

  perform pg_advisory_xact_lock(hashtext('borrowkoto:publish-terms'));
  select coalesce(max(version), 0) + 1 into next_version from public.terms_documents;
  update public.terms_documents set is_active = false where is_active;

  insert into public.terms_documents (
    title,
    version,
    file_name,
    storage_path,
    extracted_text,
    content_hash,
    is_active,
    published_by,
    published_at
  ) values (
    trim(requested_title),
    next_version,
    trim(requested_file_name),
    trim(requested_storage_path),
    trim(requested_extracted_text),
    nullif(trim(coalesce(requested_content_hash, '')), ''),
    true,
    auth.uid(),
    now()
  ) returning id into published_id;

  return published_id;
end;
$$;

revoke all on function public.publish_terms_document(text, text, text, text, text) from public;
grant execute on function public.publish_terms_document(text, text, text, text, text) to authenticated;

insert into public.terms_documents (
  title,
  version,
  file_name,
  storage_path,
  extracted_text,
  content_hash,
  is_active,
  published_at
)
select
  'Borrow Ko To Terms and Conditions',
  1,
  'Borrow_Ko_To_Terms_and_Conditions.pdf',
  'bundled/Borrow_Ko_To_Terms_and_Conditions.pdf',
  $terms$
Borrow Ko To Terms and Conditions

Rental Item Rules, Return Guidelines, and User Responsibilities

Important Notice
This document explains the rules for renting, borrowing, returning, and handling items through Borrow Ko To. Users should read it completely before activating an account or confirming a rental.

A. Legal Basis and Platform Position
Rental transactions are agreements between the participating users. Users are expected to follow the agreed rental terms, pay required charges, use items properly, and return them after the rental period. Borrow Ko To records transactions and evidence but does not declare a user guilty of a crime. Affected users may still seek barangay, civil, or legal action through proper channels.

B. Terms and Conditions

1. Acceptance of Terms
By using Borrow Ko To, the user agrees to follow the platform rules for listing, renting, borrowing, returning, purchasing, and handling items. These terms apply to item owners and renters.

2. User Account and Verification
Users must provide true, correct, and updated information. Borrow Ko To may require an active NU Baliwag registry record, contact details, address details, and other supporting information before allowing a user to list or rent items.

3. Item Listing Rules
Item owners must provide accurate item names, descriptions, conditions, prices, deposits, available quantities, pickup details, inclusions, and return rules. Owners must not list stolen, illegal, unsafe, fake, or misleading items.

4. Rental Booking
A booking is not final until the owner approves it and the required payment or deposit process is completed. The renter must review the item, price, period, quantity, pickup method, and return schedule before confirming.

5. Quantity Rule
The renter may book only the available quantity. Inventory changes follow the approved, confirmed, or paid booking status used by the platform.

6. Payment and Security Deposit
The renter agrees to pay the rental fee and required security deposit. The deposit may be applied to late fees, damage, missing parts, cleaning, repairs, replacement, or an unreturned item. Any remaining refundable balance follows the platform refund process after the owner confirms the return.

7. Item Handover
Both users should confirm handover through the platform. Borrow Ko To may require QR confirmation, item and accessory photos, a condition checklist, meetup confirmation, and date and time records.

8. Renter Duties
The renter must use the item only for its intended purpose, care for it properly, keep all accessories complete, avoid transferring it without permission, report issues immediately, return it on time, and settle valid charges.

9. Owner Duties
The owner must provide the item in the stated condition, disclose known defects, include listed accessories, follow the agreed schedule, review the return fairly, and avoid false claims.

10. Return of Item
The renter must return the item on the agreed date, time, and location. The return is completed only after the owner confirms receipt or the platform verifies the return process.

11. Late Return
Late fees may be charged under the listing and booking rules. The platform may apply the security deposit first and temporarily restrict new bookings until all remaining dues are settled.

12. Damage, Loss, or Missing Parts
The owner may file a supported claim for a damaged, incomplete, or unusable item. Evidence may include before-and-after photos, condition checklists, estimates, messages, and handover or return confirmations.

13. Failure to Return the Item
Borrow Ko To may mark a booking overdue or unresolved, notify both parties, restrict the renter account, apply the deposit, require valid payments, allow a dispute, and preserve transaction records.

14. Dispute Handling
The platform may review bookings, photos, QR records, messages, payments, meetup records, and condition checklists. Serious legal claims remain subject to the proper legal channels.

15. Prohibited Actions
Users may not list stolen or fake items, use a false identity, refuse to return an item, sell or pawn a rented item, intentionally cause damage, use an item illegally, harass another user, make false claims, or bypass the platform transaction process.

16. Platform Limitation
Borrow Ko To provides listings, bookings, communication, confirmation, payment coordination, and transaction records. It cannot guarantee that every item will be returned, but its evidence and account controls are intended to reduce risk.

17. Agreement
By accepting these terms or confirming a rental, the user agrees to the applicable listing, payment, deposit, return, dispute, and account-restriction rules of Borrow Ko To.

C. Secure Return Process
Users should verify their accounts, obtain booking approval, complete required payments, document item condition, confirm release and return, follow deadlines and reminders, and file evidence-supported disputes when necessary.

Renter Acknowledgment
I am responsible for caring for the rented item and returning it on the agreed date, time, and location. I understand that late return, damage, missing parts, or failure to return may result in fees, deposit deductions, account restrictions, disputes, or legal action depending on the circumstances.

Owner Acknowledgment
I will provide accurate item details and release the item in the stated condition. I understand that false claims, misleading details, or unsafe items may result in cancellation, dispute review, or account restriction.
  $terms$,
  'bundled-policy-v1',
  true,
  now()
where not exists (select 1 from public.terms_documents);

